[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
basic = "6hU5Vo6Njg2Mk7eaBrtLeoLLhagobC4VjPQ6zKrNP2eR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
example = "../node_modules/.bin/tsx example/index.ts"
test = "../node_modules/.bin/jest --preset ts-jest"
