[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "BgUZxfQd5vgSkcsa3d7qB7BwuCzVjxTcwJNpw9pMVQkt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# anchor test --skip-local-validator
test = "../node_modules/.bin/jest --preset ts-jest"
